### ISSUE TITLE
Missing enum datatype

### ISSUE THREAD

**Issue by yocontra** [bhoriuchi/knex-schemer#3]
Couldn't find it anywhere, seems like it was left out.

**Comment by contra** [comment]
Close with no response?

**Comment by bhoriuchi** [comment]
i responded in the other issue you opened for raw types. these were both added but i had asked for your help on testing that the new functionality worked some time back. we can re-open if its not. 

ill try to respond to each issue individually in the future and i do appreciate you opening them up.

**Comment by yocontra** [comment]
@bhoriuchi Sorry, saw this close first before seeing the other response. Deleted the comment, guess you saw it anyways - my bad.

**Comment by bhoriuchi** [comment]
@contra no worries. ive started a branch to rewrite this lib in es6 and clean up things. please feel free to open any other feature requests and ill try to fit them into the rewrite.
