### ISSUE TITLE
Support raw types

### ISSUE THREAD

**Issue by yocontra** [bhoriuchi/knex-schemer#4]
Example (PostGIS):

``` js
geo: {
    type: 'geometry(MultiPolygon, 0)',
    index: {
      indexName: `${tableName}_geo`,
      indexType: 'GIST'
    }
  }
```

in knex it would be

``` js
table.specificType('geo', 'geometry(MultiPolygon, 0)')
table.index('geo', `${tableName}_geo`, 'GIST')
```

in schemer it doesn't seem to be possible, since it throws an error on unknown types (https://github.com/bhoriuchi/knex-schemer/blob/master/lib/core/manage.js#L131-L134)

**Comment by bhoriuchi** [comment]
ill add this and enum in hopefully soon. ill also add something more elegant for unrecognized types.

**Comment by bhoriuchi** [comment]
added enum using type: "enum", also if the type specified is unrecognized within constants it will default to try creating a specificType. I am not familiar with postgis so if you can test out my latest commit and let me know if it works for you i would appreciate it.
